#!/usr/bin/env bash

RESULT="Not Installed"
if [ -f "/Library/Manufacturer/Endpoint Agent/CUI.app/Contents/Info.plist" ] ; then
RESULT=$( /usr/bin/defaults read "/Library/Manufacturer/Endpoint Agent/CUI.app/Contents/Info.plist" CFBundleVersion )
fi

/bin/echo "<result>$RESULT</result>"